/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.despesas;

import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import models.entidades.Despesas;
import models.entidades.DespesasCategorias;
import models.DAO.DespesasCategoriasDAO;
import models.entidades.TiposVariacaoDespesa;
import views.layout;

/**
 *
 * @author lucas
 */
public class AdicionarDespesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarDepesas
     */
    public AdicionarDespesas() {
        initComponents();
        this.popularSctCategorias();
    }
    
    public void popularSctCategorias(){
        DespesasCategoriasDAO dCDao = new DespesasCategoriasDAO();
        try {
            List<DespesasCategorias> listaDespesasCategorias = dCDao.getDespesasCategorias();
            //sctCategorias.addItem(listaDespesasCategorias);
            sctCategorias.addItem("Selecione");
            for (DespesasCategorias dC : listaDespesasCategorias) {
                System.out.println(dC.getNmDespesaCategoria());
                sctCategorias.addItem(dC.getNmDespesaCategoria());
                //sctCategorias.setModel(cbm);
            }
            
            //sctCategorias.add
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDespesaGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txDespesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sctCategorias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rdFixa = new javax.swing.JRadioButton();
        rdVariavel = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();

        jLabel1.setText("Despesas:");

        jLabel2.setText("Categoria:");

        sctCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sctCategoriasActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo Despesa:");

        TipoDespesaGrupo.add(rdFixa);
        rdFixa.setText("Fixa");

        TipoDespesaGrupo.add(rdVariavel);
        rdVariavel.setText("Variável");

        jLabel4.setText("Descrição:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane1.setViewportView(txaDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdFixa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                    .addComponent(rdVariavel)
                                    .addGap(31, 31, 31))
                                .addComponent(txDespesa)
                                .addComponent(sctCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnSalvar)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sctCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdFixa)
                    .addComponent(rdVariavel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sctCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sctCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sctCategoriasActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        DespesasCategorias dc = new DespesasCategorias();
        Despesas despesas = new Despesas();
        despesas.setNmDespesa(txDespesa.getText());
        despesas.setDescricao(txaDescricao.getText());
       
        if(sctCategorias.getSelectedIndex() != 0){
            dc.setIdDespesaCategoria(sctCategorias.getSelectedIndex());
            despesas.setIdDespesaCategoria(dc);
        }else{
             JOptionPane.showMessageDialog(null, "É obrigatório cadastrar a Categoria"+sctCategorias.getSelectedIndex());
        }
        
        TiposVariacaoDespesa tvd = new TiposVariacaoDespesa();
        if(rdFixa.isSelected()){
            tvd.setIdTiposVariacaoDespesa(1);
            despesas.setIdTiposVariacaoDespesa(tvd);   
        }else{
            tvd.setIdTiposVariacaoDespesa(2);
            despesas.setIdTiposVariacaoDespesa(tvd);   
        }
        try {
            despesas.salvar(despesas);
            //new Layout();
            
        } catch (Exception ex) {
            //Logger.getLogger(AdicionarDespesas.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger("Erro").log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoDespesaGrupo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdFixa;
    private javax.swing.JRadioButton rdVariavel;
    private javax.swing.JComboBox<String> sctCategorias;
    private javax.swing.JTextField txDespesa;
    private javax.swing.JTextArea txaDescricao;
    // End of variables declaration//GEN-END:variables
}
